name: BukkitCommandForward
main: ew.sr.x1c.quilt.meow.plugin.bukkit.command.forward.Main
version: 0.02
author: EW_Quilt
website: http://www.quilt.idv.tw/
description: Bukkit Command Forward Plugin
commands:
    bungeeconsole:
        description: Bungee Cord 主控台指令轉發
    bungeeplayer:
        description: Bungee Cord 玩家指令轉發